#ifndef	IEVR_VERSION_INCLUDED
#define IEVR_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define IEVR_VERSION_MAJOR	1
#define IEVR_VERSION_MINOR	1
#define IEVR_VERSION_PATCH	0
#define IEVR_VERSION_BETA	0
#define IEVR_VERSION_VERSTRING	MAKE_STR(IEVR_VERSION_MAJOR) "." MAKE_STR(IEVR_VERSION_MINOR) "." MAKE_STR(IEVR_VERSION_PATCH) "." MAKE_STR(IEVR_VERSION_BETA)

#endif
